(function(){
'use strict';
const SRC={
 auction:'https://yard.yandex.ru/courses/direct-prodvinutyy/aukcion',
 value:'https://yard.yandex.ru/courses/direct-prodvinutyy/cena-i-cennost',
 experiments:'https://yandex.ru/support/direct/ru/campaigns/experiments',
 adjustments:'https://yard.yandex.ru/courses/direct-prodvinutyy/korrektirovki-stavok',
 auto:'https://yard.yandex.ru/courses/direct-prodvinutyy/avtotargeting',
 semantics:'https://yard.yandex.ru/courses/direct-prodvinutyy/uglublyaemsya-v-rabotu-s-semantikoj',
 core:'https://yard.yandex.ru/courses/direct-prodvinutyy/sobiraem-semanticheskoe-yadro',
 operators:'https://yandex.ru/support2/wordstat/ru/content/operators',
 keywords:'https://yandex.ru/support/direct/ru/keywords/keywords',
 wordstat:'https://wordstat.yandex.ru/'
 ,segmentation:'https://yard.yandex.ru/courses/direct-prodvinutyy/segmentaciya-klyuchevyh-fraz'
 ,forecast:'https://direct.yandex.ru/registered/main.pl?cmd=advancedForecast'
 ,b2bCore:'https://b2b.yandex.ru/adv/edu/materials/semanticheskoe-yadro'
 ,xmind:'https://app.xmind.com/home/my-works'
};
const SEARCH_SITES=`avito.ru
bing.com
images.rambler.ru
images.yandex.ua
images.yandex.by
images.yandex.ru
m.uslugi.yandex.ru
maps.yandex.ru
uslugi.yandex.ru
www.cataloxy.ru
auto.ru
otzovik.com
realty.yandex.ru
ru.yandex.mobile.navigator
partprice.ru`;
const NETWORK_SITES=`com.fugo.wowguru,com.miui.player,dsp.yandex.ru,game.yandex.ru,com.zhiliaoapp.musically,dsp-webeye.yandex.ru,free.vpn.proxy.secure,dsp-minimob-ww.yandex.ru,dsp-cheetahmobile.yandex.ru,dsp-between-exchange.yandex.ru,dsp-blueseax.yandex.ru,ru.rp5.rp5weatherhorizontal,dsp-opera-browser.yandex.ru,free.vpn.unblock.proxy.vpn.master.pro,com.bravestars.faling.blocks.slide.puzzle,com.fugo.wow,dsp-huawei.yandex.ru,wi-fi.ru,com.easybrain.block.puzzle.games,com.camerasideas.instashot,com.amanotes.beathopper,com.miui.cleaner,dsp-inneractive.yandex.ru,dsp-ironsource.yandex.ru,m.video.yandex.ru,com.ihappydate,ru.sports.euro2016liverus,com.agedstudio.card.solitaire.klondike,video.like,dsp-minimob.yandex.ru,dsp-betweenx.yandex.ru,games.mail.ru,dsp-mobfox.yandex.ru,dsp-unityads.yandex.ru,com.openmygame.games.android.wordsearchsea,com.utilappsmasterpro.cleanmasterpro,games.conifer.card.solitaire.klondike.free,teskin.jewels.planet,dsp-opera-exchange.yandex.ru,com.agedstudio.hw.card.solitaire.klondike,pddmaster.ru,dsp-xapads.yandex.ru,loppipoppi.dominoes,video.yandex.ru,coloring.color.number.happy.paint.art.drawing.puzzle,com.openmygame.games.android.fillwordsoffline,dsp-mintagral.yandex.ru,com.openmygame.games.android.wordpizza,com.lenovo.anyshare.gps,com.inspiredsquare.jupiter,com.openmygame.games.android.jigsawpuzzle,dsp-start-io.yandex.ru,checko.ru,com.pixel.art.coloring.color.number`;
const STOP_WORDS=`а, будем, будет, будешь, буду, будут, будь, будьте, бы, был, была, были, было, быть, в, вам, вами, вас, весь, во, вот, все, всего, всей, всем, всеми, всему, всех, всею, всю, вся, вы, да, для, до, его, ее, ей, ему, если, есть, еще, ею, же, за, и, из, или, им, ими, их, к, как, кем, ко, когда, кого, ком, кому, которая, которое, которые, который, которую, кто, меня, мне, мной, мною, мог, моги, могите, могла, могли, могло, могу, могут, мое, моего, моей, моем, моему, моею, мои, моим, моими, моих, мой, мою, моя, мочь, мы, на, нам, нами, нас, наш, наша, наше, нашего, нашей, нашем, нашему, нашею, наши, нашим, нашими, наших, нашу, не, него, нее, ней, нем, нему, нет, нею, ним, ними, них, но, о, об, один, одна, одни, одним, одними, одних, одно, одного, одной, одном, одному, одною, одну, он, она, они, оно, от, по, при, сам, свои, своим, своими, своих, свой, свою, своя, себе, себя, собой, собою, свое, своего, своей, своем, своему, своею, та, так, такая, такие, таким, такими, таких, такого, такое, такой, таком, такому, такою, такую, те, тебе, тебя, тем, теми, тех, то, тобой, тобою, того, той, только, том, тому, тот, ту, ты, у, уже, чего, чем, чему, что, чтобы, эта, эти, этим, этими, этих, это, этого, этой, этом, этому, этот, эту, я`;
function source(url,label='Официальный источник'){return `<a class="pro91-source" href="${url}" target="_blank" rel="noopener">${label} ↗</a>`}
function check(id,text){return `<label class="pro91-check"><input type="checkbox" data-pro91-check="${id}"> <span>${text}</span></label>`}
function page(id,eyebrow,title,intro,body){if(document.getElementById(id))return document.getElementById(id);let el=document.createElement('section');el.id=id;el.className='page pro91-page';el.innerHTML=`<header class="pro91-hero"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${intro}</p></header>${body}`;document.querySelector('main').appendChild(el);return el}
function card(title,body,kind=''){return `<article class="pro91-card ${kind}"><h3>${title}</h3>${body}</article>`}
function table(rows){return `<div class="stats-wrap"><table><thead><tr>${rows[0].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function addMenu(){let items=[['Аукцион простыми словами','auctionlab'],['Цена и ценность','pricevalue'],['Wordstat и семантика','semanticslab'],['Автотаргетинг','autotargetlab'],['Корректировки','adjustmentslab']];if(typeof trackMenus!=='undefined'){items.reverse().forEach(x=>{if(!trackMenus.direct.some(y=>y[1]===x[1]))trackMenus.direct.splice(5,0,x)});if(typeof renderTrackNav==='function'&&selectedTrack==='direct')renderTrackNav()}if(typeof pageSearch!=='undefined'){[
 {page:'auctionlab',title:'Аукцион GSP и VCG',text:'аукцион ставка цена клика позиция качество прогноз CTR Поиск РСЯ GSP VCG товарная галерея'},
 {page:'pricevalue',title:'Цена и ценность конверсии',text:'CPA цена цели ценность цели доход маржа прибыль ROI ДРР предельная цена конверсии'},
 {page:'semanticslab',title:'Wordstat и семантическое ядро',text:'вордстат операторы ключевые фразы минус-слова стоп-слова семантика группы поисковые запросы площадки блокировка'},
 {page:'autotargetlab',title:'Автотаргетинг',text:'автотаргетинг алгоритм ключевые слова категории запросов Поиск РСЯ заголовок посадочная'},
 {page:'adjustmentslab',title:'Корректировки ставок',text:'корректировки пол возраст устройство регион аудитория ставка CPA ДРР перемножаются'}
 ].forEach(x=>{if(!pageSearch.some(y=>y.page===x.page))pageSearch.push(x)})}}
function buildAuction(){page('auctionlab','Директ PRO · аукцион','Аукцион без сложных слов','Аукцион — мгновенный выбор: какое объявление показать, сколько трафика дать и какую цену списать. Высокая ставка помогает, но не гарантирует первое место: учитываются качество и прогноз кликабельности.',`
 <div class="pro91-grid">${card('Главная мысль','<p><b>Ставка — потолок готовности платить, а не обязательная цена клика.</b> Система сравнивает участников для конкретного пользователя и показа. Фактическая цена обычно определяется конкуренцией и механизмом площадки.</p>','good')}${card('Что оптимизировать','<p>Не «позицию любой ценой», а прибыльную продажу. Проверяйте цепочку: качество объявления → CTR → CPC → CR → CPA/CPS → ДРР и прибыль.</p>')}</div>
 ${table([['Где','Механика','Просто'],['Тематические площадки РСЯ, внешние сети, Telegram через Директ','GSP','Победитель платит цену, связанную со ставкой следующего конкурента.'],['Поиск и поисковые площадки, Карты, список организаций','VCG','Каждая прибавка объёма трафика оплачивается по цене конкурента, который уступил этот объём.'],['Товарная галерея','VCG','У одного бизнеса может участвовать несколько товаров; для каждого рассчитываются ставка и цена.']])}
 <section class="pro91-section"><h2>Пример GSP на пальцах</h2><p>Ставки четырёх участников: 20, 15, 8 и 5 ₽. Три места получают первые три. В упрощённом учебном примере цена мест определяется следующими ставками: 15, 8 и 5 ₽. Это не означает, что достаточно всегда повысить ставку: реальный отбор учитывает качество и конкретный показ.</p></section>
 <section class="pro91-section"><h2>Пример VCG на пальцах</h2><p>Все победители сначала получают базовый объём. Более высокие позиции получают дополнительные порции трафика. За каждую такую порцию платят по конкурентной цене того участника, которого эта порция вытеснила. Поэтому цена верхней позиции — не просто «вторая ставка», а сумма уровней дополнительного трафика.</p><div class="notice"><b>Практическое решение:</b> если CPC вырос, сначала разделите данные по запросам, устройствам, регионам и времени; проверьте качество объявления и посадочной. Ставку повышайте только если предельный CPC и CPA позволяют.</div></section>
 <div class="pro91-checks">${check('auction-1','Могу объяснить различие GSP и VCG своими словами')}${check('auction-2','Понимаю, почему ставка не равна списываемой цене')}${check('auction-3','Связываю аукцион с CPA, CPS, ДРР и прибылью')}</div>${source(SRC.auction,'Урок Яндекс ЯРД')}`)}
function buildValue(){page('pricevalue','Стратегии · экономика','Цена и ценность целевого действия','Цена отвечает на вопрос «сколько готовы потратить», ценность — «сколько действие приносит или насколько оно важно». Их нельзя подменять друг другом.',`
 <div class="pro91-grid">${card('Цена конверсии / CPA','<p>Средний рекламный расход на одно целевое действие. Для бизнеса с заявками предельный CPA заявки зависит от маржи продажи и конверсии заявки в продажу.</p><code>CPA заявки max = маржа продажи × CR заявка→продажа × допустимая доля рекламы</code>')}${card('Ценность конверсии','<p>Доход или условный приоритет цели. Для ecommerce лучше передавать динамическую ценность покупки. Для этапов воронки ценность должна отражать вероятность и вклад в конечную продажу.</p><code>Ценность = CPA × (ROI + 1)</code>')}</div>
 <section class="pro91-section"><h2>Калькулятор допустимой цены заявки</h2><div class="pro91-fields"><label>Средний чек, ₽<input id="pvAov" type="number" value="120000"></label><label>Переменные расходы, ₽<input id="pvCost" type="number" value="50000"></label><label>CR заявка → продажа, %<input id="pvCr" type="number" value="20"></label><label>Допустимая доля рекламы от маржи, %<input id="pvShare" type="number" value="30"></label></div><button class="primary" onclick="pro91ValueCalc()">Рассчитать</button><div id="pvResult" class="pro91-result"></div></section>
 ${table([['Ситуация','Что указывать','Почему'],['Есть подтверждённый допустимый CPA','Цену конверсии','Алгоритм получает реалистичное ограничение расхода.'],['Покупки разного размера','Динамическую ценность','Заказ на 2 000 ₽ и 200 000 ₽ не равноценны.'],['Несколько независимых целей','Денежную или относительную ценность','Система понимает приоритет целей.'],['Нет истории и экономики','Сначала тест с бюджетом','Случайный жёсткий CPA может задушить трафик.']])}
 <div class="notice"><b>Не путайте:</b> ценность цели не обязана равняться прибыли. Документируйте метод расчёта и не назначайте микроконверсии ценнее оплаченной продажи.</div>${source(SRC.value,'Урок Яндекс ЯРД')}`)}
function buildAdjustments(){page('adjustmentslab','Управление показами','Корректировки ставок и целей','Корректировка меняет вероятность и экономику показа для сегмента. В ручной стратегии меняется ставка; в автоматической — целевой CPC, CPA или ДРР.',`
 ${table([['Категория','Пример применения','Риск'],['Устройство','Мобильные заявки чаще доходят до записи','Ошибка мобильной формы маскируется повышением ставки.'],['Пол / возраст','Подтверждена разница в продажах','Маленькая выборка создаёт ложный вывод.'],['Регион','Разная маржа или возможность обслуживания','География уже ограничена в другом месте.'],['Аудитория','Повторные посетители конвертируются лучше','Пересекающиеся сегменты и двойная интерпретация.'],['Погода / сезонность','Спрос доказуемо меняется','Ручная реакция конфликтует с обучением стратегии.']])}
 <section class="pro91-section"><h2>Как перемножаются корректировки</h2><p>Разные категории перемножаются, а не складываются. Базовая ставка 100 ₽, устройство +10%, мужчины −20%:</p><div class="pro91-fields"><label>База, ₽<input id="adjBase" type="number" value="100"></label><label>Корректировка 1, %<input id="adjOne" type="number" value="10"></label><label>Корректировка 2, %<input id="adjTwo" type="number" value="-20"></label></div><button class="primary" onclick="pro91AdjustmentCalc()">Рассчитать</button><div id="adjResult" class="pro91-result"></div></section>
 <ol class="pro91-steps"><li>Сформулируйте гипотезу и выберите одну категорию.</li><li>Проверьте достаточность продаж, а не только кликов.</li><li>Зафиксируйте базовый период и текущее значение.</li><li>Внесите изменение и не смешивайте его с другими правками.</li><li>Оцените CPA/CPS, ДРР и объём после достаточного периода.</li></ol>${source(SRC.adjustments,'Урок Яндекс ЯРД')}`)}
function buildAuto(){page('autotargetlab','Семантика · алгоритмы','Автотаргетинг: использовать вместо ключей?','Короткий ответ: не всегда. Автотаргетинг полезен для расширения и поиска скрытого спроса, а ключевые фразы дают специалисту управляемую структуру, прозрачные гипотезы и точную связь с офером.',`
 <div class="pro91-grid">${card('Как работает','<p>Алгоритм анализирует первый заголовок, текст объявления и посадочную, затем сопоставляет их с запросами и интересами. Формулировки объявления имеют приоритет.</p>')}${card('Где работает','<p>На Поиске находит запросы, которые сложно собрать вручную. В РСЯ анализирует интересы и тематику площадки; обычно работает во всех группах, кроме сценария только с ретаргетингом.</p>')}</div>
 ${table([['Подход','Сильная сторона','Когда выбирать'],['Ключевые фразы','Контроль намерения, группировки, текста и статистики','Есть понятный сформированный спрос и важна точность.'],['Автотаргетинг','Расширение, новые формулировки, скорость','Нужно найти дополнительный объём и накопить запросы.'],['Совместно','Контроль плюс расширение','Чаще всего лучший старт: ключи как база, автотаргетинг как отдельная проверяемая гипотеза.']])}
 <section class="pro91-section"><h2>Безопасный рабочий процесс</h2><ol class="pro91-steps"><li>Сделайте конкретный первый заголовок и текст.</li><li>Разделите разные услуги и намерения по группам.</li><li>Выберите допустимые категории запросов автотаргетинга.</li><li>Смотрите отчёт сразу по типу условия, категории запроса и номеру объявления.</li><li>Нерелевантные запросы исключайте; сильные запросы переносите в управляемую семантику.</li></ol></section>
 <div class="notice"><b>Почему нельзя «включить алгоритм и забыть»:</b> алгоритм оптимизирует ту цель и те данные, которые получил. Ошибочная цель, общий текст, слабая посадочная или отсутствие CRM заставят его масштабировать не тот результат.</div>${source(SRC.auto,'Урок Яндекс ЯРД')}`)}
function buildSemantics(){page('semanticslab','Рабочий инструмент · Директ','Семантическое ядро','Самостоятельный рабочий раздел: от границ продукта и карты спроса до сегментов, групп объявлений, частотности, минус‑фраз и контроля реальных запросов. Wordstat показывает формулировки и статистику спроса, но не обещает клики, заявки или продажи.',`
 <nav class="sem-toc" aria-label="Оглавление раздела"><b>Оглавление</b><a href="#sem-goal">1. Результат работы</a><a href="#sem-sources">2. Источники и инструменты</a><a href="#sem-method">3. Сбор ядра</a><a href="#sem-map">4. Семантическая карта</a><a href="#sem-segments">5. Сегментация</a><a href="#sem-frequency">6. Частотность</a><a href="#sem-groups">7. Группы объявлений</a><a href="#sem-operators">8. Операторы</a><a href="#sem-negatives">9. Минус‑фразы</a><a href="#sem-control">10. Контроль после запуска</a><a href="#sem-work">11. Рабочие поля</a></nav>
 <div class="pro91-toolbar"><a class="primary" href="${SRC.wordstat}" target="_blank" rel="noopener">Wordstat ↗</a><a href="${SRC.xmind}" target="_blank" rel="noopener">Создать карту в Xmind ↗</a><a href="${SRC.forecast}" target="_blank" rel="noopener">Проверить прогноз и частотность ↗</a><button onclick="pro91Copy('searchSites')">Копировать список для Поиска</button><button onclick="pro91Copy('networkSites')">Копировать список для сетей</button></div>
 <section class="pro91-section" id="sem-goal"><h2>Что должно получиться</h2><p>Не таблица из тысяч слов, а воспроизводимая карта «сегмент спроса → намерение → группа → объявление → посадочная → цель → экономический приоритет». Для каждой фразы должно быть понятно, почему она нужна, куда ведёт и как будет оцениваться.</p>${table([['Артефакт','Что в нём есть','Критерий готовности'],['Карта спроса','Продукт, свойства, проблемы, география, коммерческие и информационные ветви','Ветка имеет понятный смысл и не дублирует соседнюю'],['Таблица ядра','Фраза, частотность, сегмент, интент, группа, страница, статус','Нет строк без решения и посадочной'],['Список минус‑фраз','Слово/фраза, уровень, причина, дата','Каждое исключение проверено на конфликт'],['План запуска','Приоритеты, бюджет, KPI и дата проверки','Сначала запускаются сегменты с ясным спросом и экономикой']])}</section>
 <section class="pro91-section" id="sem-sources"><h2>Инструменты и роль каждого</h2>${table([['Инструмент','Для чего','Что не доказывает'],['Wordstat','Формулировки спроса, вложенные/похожие запросы, регион и динамика','Не прогнозирует продажи'],['Xmind','Визуальная карта продукта, свойств, потребностей, географии и сегментов','Не заменяет таблицу ключей и экономику'],['Прогноз бюджета Директа','Оценка показов, кликов и расходов по региону/периоду с учётом минус‑фраз','Это прогноз, а не гарантия CPC или объёма'],['Сайт, CRM, Метрика','Язык клиентов, реальные услуги, продажи и качество запросов','Исторические данные не гарантируют повторение'],['Поисковые запросы после запуска','Фактические формулировки пользователей','Один запрос без достаточной выборки не определяет всю стратегию']])}<div class="notice"><b>Практический порядок:</b> сначала создайте карту в Xmind, затем перенесите конечные ветви в таблицу, проверьте спрос и экономику, после чего сформируйте группы. Ссылка на Xmind ведёт во внешний сервис: его файлы хранятся по правилам Xmind, поэтому важные карты дополнительно экспортируйте на ПК.</div></section>
 <section class="pro91-section" id="sem-method"><h2>Методика сбора ядра</h2><ol class="pro91-steps"><li><b>Зафиксировать границы:</b> что продвигаем и не продвигаем, регион, аудитория, чек, мощность и экономика.</li><li><b>Собрать маркерные слова:</b> продукт × тип/модель × потребность × свойство × коммерческий модификатор × география.</li><li><b>Расширить:</b> Wordstat, сайт, конкуренты, подсказки, Метрика, CRM и формулировки сотрудников продаж.</li><li><b>Очистить:</b> помечать нерелевантный смысл, но не минусовать общий термин без проверки контекста.</li><li><b>Сегментировать:</b> коммерческие, географические, общие, конкурентные, альтернативные, информационные и сопутствующие.</li><li><b>Сгруппировать:</b> общее намерение, предложение, посадочная, география и экономика.</li><li><b>Назначить приоритет:</b> готовность к покупке × релевантность × маржа × объём × способность обработать спрос.</li><li><b>После запуска:</b> фактические запросы расширяют ядро и подтверждают или опровергают минусы.</li></ol><p>${source(SRC.core,'Урок о сборе семантического ядра')}${source(SRC.b2bCore,'Материал Яндекса о семантическом ядре')}</p></section>
 <section class="pro91-section" id="sem-map"><h2>Семантическая карта в Xmind</h2><p>Центр карты — конкретная услуга или продукт. Первый уровень: объект, задача клиента, свойства, цена/условия, география, аудитория, конкуренты и альтернативы. Второй уровень — реальные формулировки. Не начинайте карту со списка ключей: сначала опишите рынок и логику выбора.</p>${table([['Ветка для стоматологии','Пример','Дальнейшее решение'],['Услуга','имплантация, All-on-4, имплант','Отдельные продуктовые кластеры'],['Коммерческий модификатор','цена, стоимость, под ключ, рассрочка','Высокий приоритет при подходящей странице'],['География','Москва, СВАО, метро Отрадное','Проверить возможность обслуживания и геотаргетинг'],['Проблема/ситуация','нет зубов, сломался протез','Отдельный оффер, если клиника решает задачу'],['Информация','как проходит, противопоказания, отзывы','Отдельная роль в воронке; не смешивать CPA с горячим спросом']])}<p>${source(SRC.xmind,'Открыть Xmind')}${source(SRC.segmentation,'Урок ЯРД: семантическая карта')}</p></section>
 <section class="pro91-section" id="sem-segments"><h2>Сегментация и порядок запуска</h2>${table([['Сегмент','Пример','Когда использовать'],['Коммерческий','имплантация цена, заказать имплантацию','Обычно первый приоритет: человек ближе к выбору'],['Географический','имплантация Москва, клиника у метро','Рано, если география влияет на решение'],['Общий / широкий','имплантация зубов','Отдельный тест после понятных сегментов'],['Конкурентный','название другой клиники','Изолированно: намерение уже связано с конкурентом'],['Альтернатива','мост или имплант','Отдельное сообщение сравнения, если услуга релевантна'],['Информационный','как проходит имплантация','Контент/прогрев; не смешивать с горячим CPA'],['Сопутствующий','КТ челюсти','Только если есть доказуемая связь и подходящая страница']])}<div class="notice"><b>Частотность относительна нише.</b> В уроке ЯРД приведён учебный ориентир: менее 10 запросов за 30 дней — ультранизкая, 10–100 — низкая, 100–1000 — средняя, более 1000 — высокая. Это не универсальный стандарт и не показатель коммерческой ценности.</div>${source(SRC.segmentation,'Урок ЯРД: сегментация ключевых фраз')}</section>
 <section class="pro91-section" id="sem-frequency"><h2>Как проверять частотность и прогноз</h2><ol class="pro91-steps"><li>Выберите фактический регион оказания услуги.</li><li>Укажите период прогноза и учитывайте сезонность.</li><li>Загрузите очищенные фразы и актуальные минус‑фразы.</li><li>Сохраните дату, регион, настройки и выгрузку — иначе расчёт нельзя воспроизвести.</li><li>Сравните спрос с доступным бюджетом, прогнозным CPC и допустимым CPC из экономики.</li></ol><div class="notice"><b>Не делайте вывод «высокая частотность = выгодная фраза».</b> Высокочастотная формулировка может быть широкой и дорогой, а низкочастотная — редкой, но транзакционной. Решение принимает связка интента, стоимости, конверсии и маржи.</div>${source(SRC.forecast,'Открыть Прогноз бюджета Директа')}</section>
 <section class="pro91-section" id="sem-groups"><h2>От сегмента к группе объявлений</h2><p>Новая группа нужна, когда меняется продукт, намерение, посадочная, аудитория/условие показа или экономика. Не используйте крайности «всё в одной группе» и «один ключ — одна группа».</p>${table([['Группа','Фразы','Объявление и страница'],['Имплантация · цена · Москва','имплантация цена москва; стоимость импланта москва','Цена и варианты оплаты → /implant/cena/'],['All-on-4','all on 4 москва; все зубы на 4 имплантах','Конкретная технология → /implant/all-on-4/'],['Информационная','как проходит имплантация; противопоказания','Объясняющий материал → /blog/implant-process/']])}</section>
 <section class="pro91-section" id="sem-operators"><h2>Операторы: шпаргалка</h2>${table([['Оператор','Что фиксирует','Пример'],['-','Исключает слово','доставка -цветы'],['!','Форму слова: число, падеж, время','купить !собаку'],['+','Стоп-слово','работа +на дому'],['\" \"','Количество слов без дополнительных слов','\"купить автомобиль\"'],['[ ]','Порядок слов','билеты [из москвы в париж]'],['( ) и |','Группировка и варианты в Wordstat','(купить|заказать) диван']])}<div class="notice"><b>Не ставьте операторы автоматически везде.</b> Чем сильнее фиксация, тем уже охват. Сначала сформулируйте риск, затем применяйте оператор и проверяйте реальные запросы.</div><p>${source(SRC.operators,'Справка Wordstat')}${source(SRC.semantics,'Урок Яндекс ЯРД')}</p></section>
 <details class="pro91-details" id="sem-negatives"><summary>Минус‑фразы и официальный список стоп‑слов</summary><p>Служебные части речи и местоимения могут автоматически исключаться при отборе. Если без них меняется смысл, фиксируйте «+» или «!». Минус‑фраза должна иметь причину, уровень (группа/кампания) и проверку конфликта с полезными запросами. Список меняется и может быть неполным — сверяйтесь с источником.</p><div class="pro91-wordlist">${STOP_WORDS}</div>${source(SRC.keywords,'Актуальный список Яндекс Директа')}</details>
 <section class="pro91-section"><h2>Площадки и приложения для контроля</h2><div class="notice danger"><b>Это не официальный универсальный blacklist.</b> Списки ниже сохранены как пользовательская стартовая гипотеза. Перед исключением проверьте расход, конверсии, качество CRM и достаточность выборки. Массовая блокировка может уменьшить охват и помешать обучению стратегии.</div><div class="pro91-grid"><article><h3>Поиск: проверить отдельно</h3><textarea id="searchSites" class="pro91-list" readonly>${SEARCH_SITES}</textarea><p>Часть доменов может относиться к разным типам инвентаря. Исключайте только там, где интерфейс и отчёт действительно позволяют это сделать.</p></article><article><h3>Сети: стартовые кандидаты</h3><textarea id="networkSites" class="pro91-list" readonly>${NETWORK_SITES}</textarea><p>Не расширяйте список до сотен площадок без фактической причины. Сначала фильтруйте по расходу, конверсиям и качеству.</p></article></div></section>
 <section class="pro91-section" id="sem-control"><h2>Контроль после запуска</h2>${table([['Когда','Что смотреть','Что записать'],['Первые дни','Фактические запросы, тип условия, категория автотаргетинга, расход','Нерелевантный смысл, уровень исключения, риск конфликта'],['Еженедельно','Запрос → лид → качество → продажа → CPS/ДРР','Какие сегменты расширять, разделять или останавливать'],['После изменения','Объём, CPC, CR, качество до/после','Гипотеза, одно изменение, дата и критерий решения']])}<div class="notice"><b>Ядро не заканчивается перед запуском.</b> Это рабочая система, которая развивается по фактическим запросам и продажам. Не добавляйте минусы только потому, что фраза «не нравится»: докажите нерелевантность или плохую экономику.</div></section>
 <section class="pro91-section" id="sem-work"><h2>Рабочие поля проекта</h2><p>Заполнения сохраняются автоматически в браузере, входят в резервную копию и в Word‑отчёт раздела «Проект 0 → прибыль».</p><div class="sem-work-grid"><label><b>1. Границы продукта и цель</b><textarea data-pro91-note="sem-core-goal" oninput="state.lessonNotes['sem-core-goal']=this.value;save()" placeholder="Что продвигаем / не продвигаем / регион / результат / экономика…"></textarea></label><label><b>2. Маркерные направления</b><textarea data-pro91-note="sem-core-markers" oninput="state.lessonNotes['sem-core-markers']=this.value;save()" placeholder="Продукт × проблема × свойства × коммерческие слова × география…"></textarea></label><label><b>3. Сегменты и приоритет</b><textarea data-pro91-note="sem-core-segments" oninput="state.lessonNotes['sem-core-segments']=this.value;save()" placeholder="Коммерческий / гео / общий / конкурент / альтернатива / информационный…"></textarea></label><label><b>4. Ссылка на карту и таблицу</b><textarea data-pro91-note="sem-core-map" oninput="state.lessonNotes['sem-core-map']=this.value;save()" placeholder="Xmind / локальный файл / таблица / дата версии…"></textarea></label><label><b>5. Минус‑фразы и причины</b><textarea data-pro91-note="sem-core-negatives" oninput="state.lessonNotes['sem-core-negatives']=this.value;save()" placeholder="Минус / уровень / причина / дата / проверка конфликта…"></textarea></label><label><b>6. Решение к запуску</b><textarea data-pro91-note="sem-core-decision" oninput="state.lessonNotes['sem-core-decision']=this.value;save()" placeholder="Какие группы запускаем сначала / бюджет / KPI / дата проверки…"></textarea></label></div></section>
 <div class="pro91-checks">${check('sem-1','Зафиксировал, что продвигаем и что не продвигаем')}${check('sem-2','Создал семантическую карту и сохранил её копию')}${check('sem-3','Проверил регион, сезонность и частотность')}${check('sem-4','Сгруппировал фразы по намерению, посадочной и экономике')}${check('sem-5','Проверил операторы и минус-фразы на конфликт')}${check('sem-6','Создал регламент анализа поисковых запросов')}</div>`)}
function extendExperiments(){let root=document.getElementById('experiments');if(!root||root.querySelector('.pro91-experiments'))return;root.insertAdjacentHTML('beforeend',`<section class="pro91-section pro91-experiments"><span class="eyebrow">Официальный процесс</span><h2>A/B-эксперимент от гипотезы до решения</h2><ol class="pro91-steps"><li><b>Гипотеза:</b> одна причина, одно изменение, одна главная метрика.</li><li><b>Варианты:</b> контроль и тест должны отличаться проверяемым фактором.</li><li><b>Сегменты:</b> выберите счётчик, цель и доли аудитории; исключите пересечения.</li><li><b>До старта:</b> зафиксируйте период, минимальный объём данных и правило остановки.</li><li><b>Анализ:</b> смотрите объём, CPA/CPS, ДРР, качество CRM и статистическую погрешность.</li><li><b>Решение:</b> внедрить, отклонить, продолжить или повторить — с объяснением.</li></ol>${table([['Проверяем','Плохой тест','Корректный тест'],['Цена конверсии','Поменяли CPA, объявления и посадочную','Одинаковые условия, отличается целевой CPA'],['Креатив','Сравнили разные периоды','Одновременные сегменты одной аудитории'],['Стратегия','Остановили через два дня','Заранее задан срок и минимальная выборка']])}<div class="notice"><b>Не объявляйте победителя только по CTR.</b> Для бизнеса сравните конечную цель и качество; при небольшом числе конверсий результат может быть случайным.</div>${source(SRC.experiments,'Официальная справка Директа')}</section>`)}
function addSearchHintsInside(){let input=document.getElementById('globalSearch');if(!input)return;let id='academySearchHints';if(!document.getElementById(id)){let d=document.createElement('datalist');d.id=id;['РСЯ','аукцион','GSP','VCG','Wordstat','семантическое ядро','операторы','стоп-слова','автотаргетинг','корректировки','эксперименты','цена конверсии','ценность конверсии','площадки'].forEach(v=>d.insertAdjacentHTML('beforeend',`<option value="${v}"></option>`));document.body.appendChild(d)}input.setAttribute('list',id)}
window.pro91ValueCalc=function(){let a=+pvAov.value,c=+pvCost.value,cr=+pvCr.value/100,s=+pvShare.value/100,margin=a-c,maxSale=margin*s,maxLead=maxSale*cr;pvResult.innerHTML=`Маржа до рекламы: <b>${margin.toLocaleString('ru-RU')} ₽</b><br>Допустимый рекламный расход на продажу: <b>${maxSale.toLocaleString('ru-RU')} ₽</b><br>Ориентир максимального CPA заявки: <b>${maxLead.toLocaleString('ru-RU')} ₽</b><small>Это экономический потолок по введённым допущениям, а не обещание рынка. Добавьте постоянные расходы, возвраты и налоги, если они существенны.</small>`}
window.pro91AdjustmentCalc=function(){let base=+adjBase.value,a=1+(+adjOne.value/100),b=1+(+adjTwo.value/100),v=Math.max(0,base*a*b);adjResult.innerHTML=`${base.toLocaleString('ru-RU')} × ${a.toFixed(2)} × ${b.toFixed(2)} = <b>${v.toLocaleString('ru-RU',{maximumFractionDigits:2})} ₽</b><small>Разные категории перемножаются. Для пересекающихся аудиторий одной категории действуют отдельные правила — проверяйте актуальную справку.</small>`}
window.pro91Copy=async function(id){let el=document.getElementById(id);try{await navigator.clipboard.writeText(el.value);alert('Список скопирован. Перед применением проверьте его по фактическому отчёту.')}catch(e){el.select();document.execCommand('copy')}}
function restore(){document.querySelectorAll('[data-pro91-check]').forEach(x=>{x.checked=!!state.done['pro91-'+x.dataset.pro91Check];x.onchange=()=>{state.done['pro91-'+x.dataset.pro91Check]=x.checked;save()}});document.querySelectorAll('[data-pro91-note]').forEach(x=>x.value=state.lessonNotes[x.dataset.pro91Note]||'')}
function css(){if(document.getElementById('pro91Style'))return;let s=document.createElement('style');s.id='pro91Style';s.textContent=`.pro91-page{padding-bottom:50px}.pro91-hero{padding:28px;border-radius:22px;background:#171a16;color:#fff;margin-bottom:18px}.pro91-hero h1{font-size:clamp(30px,4vw,44px);margin:8px 0}.pro91-hero p{max-width:900px;color:#d8ddd2}.pro91-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:16px 0}.pro91-card,.pro91-section,.pro91-details,.pro91-checks{border:1px solid #d9d5ca;border-radius:16px;background:#fff;padding:20px;margin:16px 0;scroll-margin-top:78px}.pro91-card.good{border-left:5px solid var(--lime)}.pro91-card code{display:block;white-space:normal;background:#eef5dc;padding:10px;border-radius:8px}.pro91-section h2{margin-top:0}.pro91-steps{line-height:1.7}.pro91-steps li{margin:8px 0}.pro91-source{display:inline-block;margin:10px 12px 0 0;color:#315b4c;font-weight:800}.pro91-fields{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0}.pro91-fields label{font-size:12px;font-weight:800}.pro91-fields input{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:11px;border:1px solid #c9c5ba;border-radius:9px}.pro91-result{background:#171a16;color:#fff;padding:16px;border-radius:12px;margin-top:12px;line-height:1.7}.pro91-result b{color:var(--lime);font-size:20px}.pro91-result small{display:block;color:#c8cdbf}.pro91-toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}.pro91-toolbar a,.pro91-toolbar button{border:1px solid #d9d5ca;background:#fff;border-radius:10px;padding:12px 15px;font-weight:900;text-decoration:none}.pro91-toolbar .primary{background:var(--lime);border-color:var(--lime)}.pro91-list{width:100%;height:210px;box-sizing:border-box;padding:12px;font:12px/1.5 monospace;border:1px solid #ccc;border-radius:10px}.pro91-wordlist{line-height:1.75;background:#f2f0e9;padding:14px;border-radius:10px}.pro91-details summary{font-size:20px;font-weight:900;cursor:pointer}.pro91-check{display:flex;gap:10px;margin:10px 0}.notice.danger{border-left-color:#e5573e;background:#fff0eb}.sem-toc{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px!important;margin:16px 0;padding:16px;border:1px solid #d9d5ca;border-radius:15px;background:#fff}.sem-toc b{grid-column:1/-1}.sem-toc a{padding:9px 10px;border-radius:8px;background:#f0eee7;text-decoration:none;font-size:12px}.sem-toc a:hover{background:#e7f4c9}.sem-work-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.sem-work-grid label{display:grid;gap:7px}.sem-work-grid textarea{min-height:130px;padding:12px}@media(max-width:900px){.pro91-grid,.pro91-fields,.sem-work-grid{grid-template-columns:1fr}.sem-toc{grid-template-columns:1fr}.pro91-hero{padding:20px}.pro91-list{height:180px}}`;document.head.appendChild(s)}
function init(){if(typeof showPage!=='function'||!document.querySelector('main'))return setTimeout(init,150);css();buildAuction();buildValue();buildAdjustments();buildAuto();buildSemantics();extendExperiments();addMenu();addSearchHintsInside();restore();let params=new URLSearchParams(location.search),target=params.get('page'),query=params.get('q');if(['auctionlab','pricevalue','semanticslab','autotargetlab','adjustmentslab'].includes(target))showPage(target);else if(query&&typeof renderGlobalSearch==='function')renderGlobalSearch(query)}
setTimeout(init,250);
})();
