const ROUTES={
 home:{file:'index.html',title:'Главная'},project:{file:'project.html',title:'Проект 0 → прибыль'},direct:{file:'direct.html',title:'Яндекс Директ'},rsya:{file:'rsya.html',title:'РСЯ'},metrika:{file:'metrika.html',title:'Яндекс Метрика'},seo:{file:'seo.html',title:'SEO'},formulas:{file:'formulas.html',title:'Формулы'},cases:{file:'cases.html',title:'Кейсы'},practice:{file:'practice.html',title:'Практика'},help:{file:'help.html',title:'Справочник'}
};
const SECTIONS={
 project:[['Методичка 0 → прибыль','page=launchplanner'],['Wordstat и семантика','page=semanticslab&track=direct'],['Ведение проекта','page=journey'],['Контроль','page=control'],['Медиаплан','page=mediaplan'],['Юнит-экономика','page=unit'],['Журнал задач','page=taskjournal']],
 direct:[['Курсы Директа','page=courses&course=direct&track=direct'],['Продвижение','page=promotion&track=direct'],['Аукцион','page=auctionlab&track=direct'],['Цена и ценность','page=pricevalue&track=direct'],['Поиск и семантика','page=semanticslab&track=direct'],['Автотаргетинг','page=autotargetlab&track=direct'],['Корректировки','page=adjustmentslab&track=direct'],['Эксперименты','page=experiments&track=direct'],['Типы объявлений','page=adblocks&track=direct'],['ЕПК','page=epk&track=direct'],['Кабинет','page=cabinet&track=direct'],['Настройка РК','page=accountsetup&track=direct'],['Оптимизация','page=optimization&track=direct']],
 rsya:[['Основы РСЯ','page=rsya&track=direct'],['Аудитории','page=rsya&track=direct'],['Ретаргетинг','page=rsya&track=direct'],['Креативы','page=adblocks&track=direct'],['A/B-тесты','page=experiments&track=direct'],['Оптимизация','page=optimization&track=direct']],
 metrika:[['Курс Метрики','page=courses&course=metrika&track=metrika'],['Основы','track=metrika&topic=overview'],['Цели','track=metrika&topic=goals'],['События','track=metrika&topic=events'],['CRM и офлайн','page=analytics&track=metrika'],['Качество данных','track=metrika&topic=quality'],['Аудит','track=metrika&topic=audit'],['Ведение проекта','track=metrika&topic=project']],
 seo:[['Обзор SEO','track=seo&topic=overview'],['Органический трафик','track=seo&topic=organic'],['Семантика','track=seo&topic=semantics'],['Структура сайта','track=seo&topic=structure'],['Контент','track=seo&topic=content'],['On-page','track=seo&topic=onpage'],['PBN и риски','track=seo&topic=pbn'],['Ведение проекта','track=seo&topic=project']],
 formulas:[['Все формулы','page=formulas'],['Юнит-экономика','page=unit'],['Медиаплан','page=mediaplan'],['Полная воронка','page=formulas']],
 cases:[['Все кейсы','page=practice'],['Медицина','page=practice'],['Ecommerce','page=practice'],['Услуги','page=practice'],['B2B','page=practice']],
 practice:[['Проверка знаний','page=practice'],['Практический экзамен','page=professionalexam'],['Регламенты','page=regulations'],['Базовый чек-лист','page=yandexchecklist']],
 help:[['Официальная справка','page=directhelp'],['Термины','page=terms'],['Как пользоваться','page=userguide'],['Заметки','page=notes']]
};
function academyUrl(query){return 'academy.html?embed=1&'+query}
function openSection(query,button){let frame=document.getElementById('academyFrame');if(!frame)return;frame.src=academyUrl(query);document.querySelectorAll('.section-nav button').forEach(x=>x.classList.toggle('active',x===button));history.replaceState(null,'',location.pathname+'#'+encodeURIComponent(query))}
const SEARCH_HINTS=['РСЯ','аукцион GSP VCG','автотаргетинг','ключевые слова','семантическое ядро','Wordstat','операторы ключевых слов','минус-слова','стоп-слова','корректировки ставок','A/B-эксперименты','цена конверсии CPA','ценность конверсии','площадки для блокировки','ДРР','CPS','CPO','юнит-экономика','Метрика','офлайн-конверсии'];
function attachSearchHints(){if(!document.getElementById('searchHints'))document.body.insertAdjacentHTML('beforeend','<datalist id="searchHints">'+SEARCH_HINTS.map(x=>'<option value="'+x+'"></option>').join('')+'</datalist>');document.querySelectorAll('.search input[type="search"]').forEach(x=>x.setAttribute('list','searchHints'))}
function initPortal(){let route=document.body.dataset.route||'home',nav=document.getElementById('routeNav');if(nav)nav.innerHTML=Object.entries(ROUTES).map(([id,x])=>`<a href="${x.file}" class="${id===route?'active':''}">${x.title}</a>`).join('');let sections=SECTIONS[route]||[],bar=document.getElementById('sectionNav');if(bar){bar.innerHTML=sections.map((x,i)=>`<button class="${i===0?'active':''}" onclick="openSection('${x[1]}',this)">${x[0]}</button>`).join('');let hash=location.hash?decodeURIComponent(location.hash.slice(1)):sections[0]?.[1];let selected=sections.findIndex(x=>x[1]===hash);if(hash)document.getElementById('academyFrame').src=academyUrl(hash);if(selected>=0){[...bar.children].forEach((x,i)=>x.classList.toggle('active',i===selected))}}let form=document.getElementById('portalSearch');if(form)form.onsubmit=e=>{e.preventDefault();let q=form.elements.q.value.trim();if(q)location.href='search.html?q='+encodeURIComponent(q)};attachSearchHints()}
document.addEventListener('DOMContentLoaded',initPortal);
